DROP TABLE IF EXISTS api_auth;
DROP TABLE IF EXISTS sessions;

CREATE TABLE api_auth (
    user_id INTEGER PRIMARY KEY,
    user_key TEXT UNIQUE NOT NULL
);

CREATE TABLE sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    auth_handle TEXT UNIQUE,
    auth_key TEXT UNIQUE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author_discord_id TEXT UNIQUE NOT NULL,
    finished BOOLEAN NOT NULL DEFAULT FALSE
);
